# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-20 20:18

from exceptions import IOError
import os
from shutil import move

from django.conf import settings

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0014_auto_20170705_2333'),
    ]

    def change_pictures_paths(apps, schema_editor):
        # We can't import the Photo model directly as it may be a newer
        # version than this migration expects. We use the historical version.
        Photo = apps.get_model('trips', 'Photo')
        for photo in Photo.objects.all().select_related('trip_day'):
            old_name = photo.photo.name.split('/')[-1]
            new_name = os.path.join(
                str(photo.trip_day.trip_id), str(photo.trip_day_id), old_name)
            old_path = os.path.join(settings.MEDIA_ROOT, photo.photo.name)
            new_path = os.path.join(settings.MEDIA_ROOT, new_name)
            photo.photo.name = new_name
            photo.save()
            if not os.path.exists(os.path.dirname(new_path)):
                os.makedirs(os.path.dirname(new_path))
            try:
                move(old_path, new_path)
            except IOError:
                continue

    operations = [
        migrations.RunPython(change_pictures_paths),
    ]
